### ISSUE TITLE
Release a new version?

### ISSUE THREAD

**Issue by unnawut** [polleverywhere/chaperon#17]
Could you release a new version?

We're using this library and experienced a few occasions where mix tries to lock `httpoison` down to `v1.*.*` and it conflicts with chaperon's current requirement of `~> 0.11.1`. I see that you [bumped httpoison version already](https://github.com/polleverywhere/chaperon/commit/c9928037d373fcd108fc8c619c9f56db270bba4f) but the latest release was [Sep 6, 2018](https://github.com/polleverywhere/chaperon/releases).

Thanks!

**Comment by bakkdoor** [comment]
Hey! Yeah a new release is coming soon. I'm currently in the middle of a new set of features but those should be done soon and then I will make a new release. Thanks for your patience!

**Comment by bakkdoor** [comment]
New release is out: https://hex.pm/packages/chaperon/0.3.0
