### ISSUE TITLE
Passing list of parameters for iteration

### ISSUE THREAD

**Issue by ghost** [polleverywhere/chaperon#4]
I believe more information about how the session feature works when it comes to passing parameters to a loadtest. 

I get different behavior for different things. When using the back ground noise example the following works:

       def run(session) do
           Enum.map(["foo","bar","tar"], &(async(session, :search, [&1])))
           |> Enum.map(await/1)
       end

This is in the iex though. 

however if try to perform the following with a value list that is generated at the scenario definition level using the following: 

		Enum.map(session.config.search.value, &(async(session, :search_call, [&1])))
		|> Enum.map(&await(&1))

I get some error. I believe it is related to await expecting a session + map but gets a list of session instead. I also tried the following:
 
                  Enum.map(session.config.search.value, &get(session, "query_range", params: [query: &1, start: start, end: time_end, step: step]))

This cause a similar error, I tried to put this in to run. The intention was to move it then perform an async call. 

I have also had errors based on add metrics not being able to deal with list. 

I could try running async task using this example instead of the Session.await/2:
Task.async, however I think this will be an overkill since all I want to do is perform get request that iterates through a list of parameters. 

I know that there is Scenario definition, but I am not sure how many of this I can spawn. I can define a a parameter per scenario in the list that gets targeted by runloadtest. How many of these can I have ? & Is there an alternative method that you recommend passing multiple parameters when run a load test.

**Comment by bakkdoor** [comment]
Hey! I'm not exactly sure I understand your question but if all you're trying to do is make a bunch of concurrent `POST` requests to a configurable list of endpoints and then await them all at the end, you can try something like: 

```elixir
def run(session) do
  session
  |> concurrent_search(session.config.search.values)
end

def concurrent_search(session, []) do
  session
  |> await_all(:search) # this awaits all tasks running `search` function
end

def concurrent_search(session, [val | values]) do
  session
  |> async(:search, [val])
  |> concurrent_search(values) # repeat for remaining search values
end

def search(session, val) do
  session
  |> post("/search", json: %{query: val})
end
```

Also, you shouldn't be too worried about creating & spawning new scenarios. Each running session runs its scenario (which can be composed of multiple other scenarios etc.) inside a supervised `Task` process (ultimately spawned via `Task.Supervisor.async`). Spawning tasks & processes in Elixir isn't scary so unless you actually run into some bottlenecks, I would just map your logic as naturally to scenarios as it makes logical sense to you.

Could you explain what exactly you mean by passing multiple parameters to a scenario? When running a Scenario for a LoadTest, you can pass a Map of key value bindings (stored in `session.config`) which allows you to pass as many parameters to a Scenario as you want. You can also write your own generic Scenarios, that e.g. run other scenarios in a certain pattern (e.g. run all concurrently or some other combination of concurrent/sequential groupings of a given list of Scenarios) by calling out to `Session.run_scenario/2` & `Session.run_scenario/4`)

If you haven't looked at it, I also recommend checking out the [API documentation](https://hexdocs.pm/chaperon/api-reference.html)

Let me know if you have any other questions.

**Comment by ghost** [comment]
Thanks a lot this was really great advise. I cant believe I didn't notice that sooner. I am kinda of noob to elixir and I didn't notice the recursive function or maybe I did not have a good understanding of Async task. 

What you recommended worked brilliantly. I had explored the API docs and they where very well written to be honest with you. 

I tired a number of different things and encountered a number of different error in regards based on the various different session where put together. This involved things such as the results not meshing together properly towards the end. One example would be the async the tasks. I have only read the programming elixir book up to just before the OTP & Task chapters. 

However thanks a lot I will continue to use this and hopefully contribute what I can, when the time comes.

**Comment by bakkdoor** [comment]
Cool, glad I could help!
Generally, what I probably should have mentioned in my post earlier, is that all of the Scenario functions (those handling `Session` structs) should always return the session and also not drop the result of anything that returns a session.

So another way to implement this would be using `Enum.reduce` instead of your attempt of using `Enum.map` because you'll want to keep track of the `session` value and update it until the end, since any call to `Session.async` will return an updated `session` value that will hold information on the newly spawned async task. It will store a `Task` value inside `session` which is what `Session.await_all` uses to actually await the spawned tasks.
`Enum.map` didn't work here because it just returns the mapped list but instead you'd want it to return the final `session` and inject that (via `Enum.reduce`) into each iteration so it can be updated accordingly.

In either way, sometimes it's just easier to write down the function definitions with the proper pattern matches as I did in my example above. I find it pretty easy to read & understand, too. :)
